version: "3.8"
services:
  nytaxi_db:
    restart: always
    image: postgres:latest
    container_name: nytaxi_db_cont
    env_file: .env
    # environment:
    #   POSTGRES_USER: ${DB_USERNAME}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - nytaxi_pg:/var/lib/postgresql/data
    networks:
      - nytaxi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  sql_ingestor:
    build:
      context: .
    image: sql_ingestion
    container_name: sql_ingestion_cont
    env_file: .env
    command: --url https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-11.parquet --table yellow_taxi --db_host nytaxi_db
    networks:
      - nytaxi_network
    depends_on:
      nytaxi_db:
        condition: service_healthy
volumes:
  nytaxi_pg:

networks:
  nytaxi_network:
    driver: bridge
